sets.exported={
    main="Kaja Sword",
    sub={ name="Nibiru Cudgel", augments={'MP+46','INT+9','"Mag.Atk.Bns."+13',}},
    ammo="Hydrocera",
    head="Jhakri Coronal +2",
    body="Jhakri Robe +2",
    hands="Jhakri Cuffs +2",
    legs="Aya. Cosciales +2",
    feet="Jhakri Pigaches +2",
    neck="Stoicheion Medal",
    waist="Eschan Stone",
    left_ear={ name="Moonshade Earring", augments={'"Mag.Atk.Bns."+4','TP Bonus +250',}},
    right_ear="Friomisi Earring",
    left_ring="Fenrir Ring",
    right_ring="Fenrir Ring",
    back={ name="Rosmerta's Cape", augments={'STR+20','Accuracy+20 Attack+20','Weapon skill damage +10%',}},
}