sets.exported={
    main={ name="Nibiru Cudgel", augments={'MP+49','INT+9','"Mag.Atk.Bns."+14',}},
    sub={ name="Nibiru Cudgel", augments={'MP+46','INT+9','"Mag.Atk.Bns."+13',}},
    ammo="Hydrocera",
    head="Pixie Hairpin +1",
    body="Jhakri Robe +2",
    hands="Jhakri Cuffs +2",
    legs="Aya. Cosciales +2",
    feet="Jhakri Pigaches +2",
    neck="Stoicheion Medal",
    waist="Eschan Stone",
    left_ear="Friomisi Earring",
    right_ear="Hecate's Earring",
    left_ring="Archon Ring",
    right_ring="Fenrir Ring",
    back={ name="Rosmerta's Cape", augments={'STR+20','Accuracy+20 Attack+20','Weapon skill damage +10%',}},
}