sets.exported={
    main={ name="Nibiru Cudgel", augments={'MP+49','INT+9','"Mag.Atk.Bns."+14',}},
    sub={ name="Nibiru Cudgel", augments={'MP+46','INT+9','"Mag.Atk.Bns."+13',}},
    ammo="Staunch Tathlum",
    head="Jhakri Coronal +2",
    body="Jhakri Robe +2",
    hands="Jhakri Cuffs +2",
    legs="Aya. Cosciales +2",
    feet="Jhakri Pigaches +2",
    neck="Mirage Stole +1",
    waist="Witful Belt",
    left_ear="Mendi. Earring",
    right_ear="Dominance Earring",
    left_ring="Jhakri Ring",
    right_ring="Stikini Ring",
    back="Swith Cape",
}