sets.exported={
    main="Oranyan",
    sub="Clemency Grip",
    ammo="Staunch Tathlum",
    head={ name="Viti. Chapeau +2", augments={'Enfeebling Magic duration','Magic Accuracy',}},
    body="Jhakri Robe +2",
    hands="Aya. Manopolas +2",
    legs={ name="Carmine Cuisses +1", augments={'Accuracy+20','Attack+12','"Dual Wield"+6',}},
    feet="Aya. Gambieras +2",
    neck="Loricate Torque +1",
    waist="Gishdubar Sash",
    left_ear="Merman's Earring",
    right_ear="Loquac. Earring",
    left_ring="Aquasoul Ring",
    right_ring="Griffon Ring",
    back="Moonbeam Cape",
}