sets.exported={
    main="Malignance Sword",
    sub="Ochain",
    ammo="Incantor Stone",
    head={ name="Souv. Schaller +1", augments={'HP+105','Enmity+9','Potency of "Cure" effect received +15%',}},
    body="Rev. Surcoat +2",
    hands="Macabre Gaunt. +1",
    legs={ name="Souv. Diechlings +1", augments={'HP+105','Enmity+9','Potency of "Cure" effect received +15%',}},
    feet={ name="Souveran Schuhs +1", augments={'HP+105','Enmity+9','Potency of "Cure" effect received +15%',}},
    neck="Unmoving Collar",
    waist="Creed Baudrier",
    left_ear="Friomisi Earring",
    right_ear="Odnowa Earring +1",
    left_ring="Supershear Ring",
    right_ring="Moonbeam Ring",
    back={ name="Rudianos's Mantle", augments={'STR+20','Accuracy+20 Attack+20','Weapon skill damage +10%',}},
}