sets.exported={
    main="Pukulatmuj +1",
    sub={ name="Forfend +1", augments={'Path: A',}},
    ammo="Staunch Tathlum",
    head="Malignance Chapeau",
    body={ name="Nyame Mail", augments={'Path: B',}},
    hands="Malignance Gloves",
    legs={ name="Nyame Flanchard", augments={'Path: B',}},
    feet="Malignance Boots",
    neck="Loricate Torque +1",
    waist="Gishdubar Sash",
    left_ear="Odnowa Earring +1",
    right_ear="Infused Earring",
    left_ring="Warden's Ring",
    right_ring="Stikini Ring",
    back={ name="Sucellos's Cape", augments={'DEX+20','Accuracy+20 Attack+20','"Dual Wield"+10','Damage taken-5%',}},
}