sets.exported={
    main="Excalibur",
    sub={ name="Machaera +2", augments={'TP Bonus +1000',}},
    ammo="Staunch Tathlum",
    head={ name="Viti. Chapeau +3", augments={'Enfeebling Magic duration','Magic Accuracy',}},
    body="Malignance Tabard",
    hands="Jhakri Cuffs +2",
    legs="Malignance Tights",
    feet={ name="Vitiation Boots +3", augments={'Immunobreak Chance',}},
    neck="Thunder Gorget",
    waist="Prosilio Belt",
    left_ear={ name="Moonshade Earring", augments={'Attack+4','TP Bonus +250',}},
    right_ear="Ishvara Earring",
    left_ring="Rufescent Ring",
    right_ring="Karieyh Ring",
    back={ name="Sucellos's Cape", augments={'STR+20','Accuracy+20 Attack+20','Weapon skill damage +10%',}},
}