sets.exported={
    main="Shining One",
    sub="Nepenthe Grip",
    ammo="Focal Orb",
    head={ name="Valorous Mask", augments={'Attack+15','Weapon skill damage +2%','Accuracy+6',}},
    body="Nzingha Cuirass",
    hands="Sulev. Gauntlets +2",
    legs={ name="Carmine Cuisses +1", augments={'Accuracy+20','Attack+12','"Dual Wield"+6',}},
    feet="Sulev. Leggings +2",
    neck="Loricate Torque +1",
    waist="Ioskeha Belt",
    left_ear="Brutal Earring",
    right_ear="Merman's Earring",
    left_ring="Karieyh Ring",
    right_ring="Moonbeam Ring",
    back="Moonbeam Cape",
}