sets.exported={
    main="Naegling",
    sub="Gleti's Knife",
    range={ name="Anarchy +2", augments={'Delay:+60','TP Bonus +1000',}},
    ammo="Chrono Bullet",
    head={ name="Herculean Helm", augments={'Attack+22','Weapon skill damage +3%','Accuracy+5',}},
    body="Meg. Cuirie +2",
    hands="Meg. Gloves +2",
    legs={ name="Herculean Trousers", augments={'Rng.Acc.+25 Rng.Atk.+25','Weapon skill damage +4%','STR+7','Rng.Acc.+6',}},
    feet="Meg. Jam. +2",
    neck="Light Gorget",
    waist="Light Belt",
    left_ear="Ishvara Earring",
    right_ear={ name="Moonshade Earring", augments={'Attack+4','TP Bonus +250',}},
    left_ring="Karieyh Ring",
    right_ring="Apate Ring",
    back={ name="Belenus's Cape", augments={'AGI+20','Rng.Acc.+20 Rng.Atk.+20','Weapon skill damage +10%',}},
}