sets.exported={
    main="Tauret",
    sub={ name="Taming Sari", augments={'STR+10','DEX+10','DMG:+15','"Treasure Hunter"+1',}},
    ammo="Yetshila",
    head="Malignance Chapeau",
    body="Malignance Tabard",
    hands={ name="Plun. Armlets +1", augments={'Enhances "Perfect Dodge" effect',}},
    legs={ name="Herculean Trousers", augments={'STR+2','Weapon skill damage +2%','"Treasure Hunter"+2','Mag. Acc.+5 "Mag.Atk.Bns."+5',}},
    feet="Skulk. Poulaines +1",
    neck="Loricate Torque +1",
    waist="Windbuffet Belt +1",
    left_ear="Brutal Earring",
    right_ear="Sherida Earring",
    left_ring="Moonbeam Ring",
    right_ring="Moonbeam Ring",
    back={ name="Toutatis's Cape", augments={'DEX+20','Accuracy+20 Attack+20','"Dbl.Atk."+10',}},
}