sets.exported={
    main="Tauret",
    sub="Gleti's Knife",
    range="Fomalhaut",
    ammo="Chrono Bullet",
    head="Ikenga's Hat",
    body={ name="Ikenga's Vest", augments={'Path: A',}},
    hands="Meg. Gloves +2",
    legs={ name="Herculean Trousers", augments={'Rng.Acc.+25 Rng.Atk.+25','Weapon skill damage +4%','STR+7','Rng.Acc.+6',}},
    feet="Ikenga's Clogs",
    neck="Light Gorget",
    waist="Light Belt",
    left_ear={ name="Moonshade Earring", augments={'Attack+4','TP Bonus +250',}},
    right_ear="Ishvara Earring",
    left_ring="Karieyh Ring",
    right_ring="Apate Ring",
    back={ name="Belenus's Cape", augments={'AGI+20','Rng.Acc.+20 Rng.Atk.+20','Weapon skill damage +10%',}},
}