sets.exported={
    main="Qutrub Knife",
    sub="Ceremonial Dagger",
    ammo="Regal Gem",
    head="Malignance Chapeau",
    body="Malignance Tabard",
    hands="Malignance Gloves",
    legs="Malignance Tights",
    feet={ name="Vitiation Boots +2", augments={'Immunobreak Chance',}},
    neck={ name="Dls. Torque +2", augments={'Path: A',}},
    waist="Windbuffet Belt +1",
    left_ear="Snotra Earring",
    right_ear="Malignance Earring",
    left_ring="Kishar Ring",
    right_ring="Chirich Ring",
    back={ name="Sucellos's Cape", augments={'MND+20','Mag. Acc+20 /Mag. Dmg.+20','MND+10','Weapon skill damage +10%',}},
}