sets.exported={
    main="Naegling",
    sub={ name="Rostam", augments={'Path: C',}},
    range="Fomalhaut",
    ammo="Chrono Bullet",
    head="Nyame Helm",
    body="Laksa. Frac +3",
    hands="Nyame Gauntlets",
    legs="Nyame Flanchard",
    feet={ name="Lanun Bottes +3", augments={'Enhances "Wild Card" effect',}},
    neck={ name="Comm. Charm +1", augments={'Path: A',}},
    waist="Eschan Stone",
    left_ear={ name="Moonshade Earring", augments={'Attack+4','TP Bonus +250',}},
    right_ear="Friomisi Earring",
    left_ring="Apate Ring",
    right_ring="Karieyh Ring",
    back={ name="Camulus's Mantle", augments={'AGI+20','Mag. Acc+20 /Mag. Dmg.+20','AGI+10','Weapon skill damage +10%',}},
}