sets.exported={
    main="Nirvana",
    sub="Elan Strap",
    ammo="Sancus Sachet",
    head="Beckoner's Horn +1",
    body="Tali'ah Manteel +1",
    hands={ name="Glyphic Bracers", augments={'Inc. Sp. "Blood Pact" magic burst dmg.',}},
    legs="Tali'ah Sera. +1",
    feet="Tali'ah Crackows +1",
    neck="Shulmanu Collar",
    waist="Windbuffet Belt +1",
    left_ear="Digni. Earring",
    right_ear="Dedition Earring",
    left_ring="Chirich Ring",
    right_ring="Rajas Ring",
    back="Moonbeam Cape",
}