sets.exported={
    main="Tauret",
    sub="Gleti's Knife",
    range="Fomalhaut",
    ammo="Chrono Bullet",
    body={ name="Cohort Cloak +1", augments={'Path: A',}},
    hands={ name="Carmine Fin. Ga. +1", augments={'Rng.Atk.+20','"Mag.Atk.Bns."+12','"Store TP"+6',}},
    legs={ name="Herculean Trousers", augments={'Weapon skill damage +3%','Accuracy+15','Magic Damage +17','Accuracy+8 Attack+8','Mag. Acc.+20 "Mag.Atk.Bns."+20',}},
    feet={ name="Herculean Boots", augments={'Mag. Acc.+16 "Mag.Atk.Bns."+16','Crit.hit rate+2','MND+1','"Mag.Atk.Bns."+14',}},
    neck="Sanctity Necklace",
    waist="Eschan Stone",
    left_ear={ name="Moonshade Earring", augments={'Attack+4','TP Bonus +250',}},
    right_ear="Friomisi Earring",
    left_ring="Karieyh Ring",
    right_ring="Apate Ring",
    back={ name="Belenus's Cape", augments={'AGI+20','Rng.Acc.+20 Rng.Atk.+20','AGI+10','Weapon skill damage +10%',}},
}